### ISSUE TITLE
API's To Integrate

### ISSUE THREAD

**Issue by antoni909** [HodoPile/HodoPile#9]
**Selected API's**

- [x] Collect Official Travel Advisories issued by Governments around the world [Travel Advisory.info](https://www.travel-advisory.info)

- [x] Unsplash image library [docs](https://unsplash.com/developers)

**API's Of Interest**

- [x] Pinterist [API docs](https://developers.pinterest.com/docs/getting-started/scopes/)

- [x] Amadeus API/SDK [gh](https://developers.amadeus.com/get-started/get-started-with-self-service-apis-335), [docs](https://developers.amadeus.com/get-started/get-started-with-self-service-apis-335)

**Comment by jmcmg1231** [comment]
https://tripadvisor16.p.rapidapi.com/api/v1/rentals/searchLocation

api key 12176dade8mshb04d3a635edd4c9p11dd10jsne0433ed12ce4
